version: '3'
services:
  theatre-db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      retries: 5
      timeout: 30s
    restart: always

  elastic_search:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5
      timeout: 10s
    restart: always

  etl_service:
    build: etl
    container_name: elt
    env_file:
      - .env
    depends_on:
      theatre-db:
        condition: service_healthy
      elastic_search:
        condition: service_healthy